### ISSUE TITLE
sdk不支持配置proxy

### ISSUE THREAD

**Issue by tdp100** [yunify/qingcloud-sdk-python#1]
当前的sdk中的http请求不支持配置proxy，能否提供一下该功能

**Comment by Xuanwo** [comment]
@Sunight 
Hello，根据[文档](https://docs.python.org/2.7/library/httplib.html?highlight=httplib.httpconnection#httplib.HTTPConnection)，我这里应该是要建立一个到代理服务器的HTTP链接，但是sdk本身是要和qingcloud通讯的，这个proxy功能怎么实现更合适呢？
