### ISSUE TITLE
能把 cli 的代码也建个 repo 么

### ISSUE THREAD

**Issue by unionx** [yunify/qingcloud-sdk-python#3]
这两个库不支持 py3，我想修复一下这个问题

**Comment by Sunight** [comment]
hi，帝归，谢谢你的建议，cli 会在近期整理一下代码并放到 github。
之前有次提交就是为了 py3 的兼容性，可能后来的代码又破坏了，我们会调试一下，也欢迎 pr ：）

**Comment by Sunight** [comment]
hi，帝归，谢谢你的建议，cli 会在近期整理一下代码并放到 github。
之前有次提交就是为了 py3 的兼容性，可能后来的代码又破坏了，我们会调试一下，也欢迎 pr ：）

**Comment by unionx** [comment]
ok，我就是想自己来修复一下 py3 的兼容性的

**Comment by Sunight** [comment]
@unionx 明白。目前最新版本的 sdk 和 cli 我在 python3.3 上测过，可以正常执行。你是用那个版本？以及报错是什么？

\# python -V
Python 3.3.3

### sdk
\# python
Python 3.3.3 (default, Jan  7 2015, 23:30:55)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
> import qingcloud.iaas
> conn = qingcloud.iaas.connect_to_zone('pek2', 'XDKYIJGVHMOFCQRTOWKD', '9ZFghTcKUM7X0laAiWZBZ6gq35LlHXkR3aX3LjdX')
> conn.describe_instances()
>{'instance_set': [{'transition_status': '', 'vcpus_current': 2, 'owner': 'usr-FKLksuUv', 'instance_name': 'mysql instance'.....


### cli
\# qingcloud iaas describe-instances:
  {
    "ret_code": 0,
    "instance_set": [
      {
        "description": null,
        "memory_current": 1024,
....

**Comment by unionx** [comment]
我之前直接用 pip 安装的 qingcloud-sdk

我又看了一下，版本是 qingcloud-sdk-0.9.5

```
$ sudo -H pip3 install qingcloud-sdk
Downloading/unpacking qingcloud-sdk
  Downloading qingcloud-sdk-0.9.5.tar.gz
  Running setup.py (path:/tmp/pip_build_root/qingcloud-sdk/setup.py) egg_info for package qingcloud-sdk

Requirement already satisfied (use --upgrade to upgrade): PyYAML>=3.1 in /usr/local/lib/python3.4/dist-packages (from qingcloud-sdk)
Installing collected packages: qingcloud-sdk
  Running setup.py install for qingcloud-sdk

    Skipping installation of /usr/local/lib/python3.4/dist-packages/qingcloud/__init__.py (namespace package)
    Installing /usr/local/lib/python3.4/dist-packages/qingcloud_sdk-0.9.5-nspkg.pth
      File "/usr/local/lib/python3.4/dist-packages/qingcloud/iaas/connection.py", line 38
        print json_dump(request)
                      ^
    SyntaxError: invalid syntax

Successfully installed qingcloud-sdk
Cleaning up...
```

**Comment by Sunight** [comment]
hi，我提交了 fix，你可以直接通过 git 下载最新版本。应该是兼容了 py3。
pip 的改动会随着下个版本更新上去。

**Comment by Sunight** [comment]
hi @unionx CLI 也放到 github 了

**Comment by unionx** [comment]
@Sunight thx!
